apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: t1ft4nyrf-nodejs 
  janus-idp.io/tekton: t1ft4nyrf-nodejs
  backstage.io/kubernetes-id: t1ft4nyrf-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t1ft4nyrf-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  